import type { Response } from 'express'
import type { ConversationShareRecord } from './conversationShareStore.js'

type ShareLocale = 'en' | 'zh-CN'

const WIDTH = 1_200
const MARGIN = 72
const CONTENT_WIDTH = WIDTH - MARGIN * 2
const MAX_HEIGHT = 14_000
const BODY_FONT_SIZE = 27
const BODY_LINE_HEIGHT = 44

function escapeXml(value: string): string {
  return value.replace(/[&<>'"]/gu, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
  })[character] ?? character)
}

function localeOf(share: ConversationShareRecord): ShareLocale {
  return share.snapshot.locale === 'en' ? 'en' : 'zh-CN'
}

function formatDate(value: string | null, locale: ShareLocale): string {
  if (!value) return locale === 'zh-CN' ? '永久有效' : 'Never expires'
  const time = Date.parse(value)
  if (!Number.isFinite(time)) return locale === 'zh-CN' ? '有效期未知' : 'Expiry unavailable'
  return new Intl.DateTimeFormat(locale, {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'Asia/Shanghai',
  }).format(new Date(time))
}

function plainMarkdown(value: string, locale: ShareLocale): string {
  return value
    .replace(/!\[([^\]]*)\]\([^)]*\)/gu, (_match, alt: string) => alt || (locale === 'zh-CN' ? '[图片]' : '[Image]'))
    .replace(/\[([^\]]+)\]\(([^)]+)\)/gu, '$1')
    .replace(/^\s{0,3}#{1,6}\s+/gmu, '')
    .replace(/\*\*([^*]+)\*\*/gu, '$1')
    .replace(/__([^_]+)__/gu, '$1')
    .replace(/`([^`]+)`/gu, '$1')
    .replace(/^\s*>\s?/gmu, '│ ')
    .replace(/\r\n?/gu, '\n')
    .trim()
}

function visualUnits(character: string): number {
  if (/\s/u.test(character)) return 0.42
  return /[\u0000-\u00ff]/u.test(character) ? 0.56 : 1
}

function wrapLine(value: string, maxUnits: number): string[] {
  if (!value) return ['']
  const lines: string[] = []
  let current = ''
  let units = 0
  for (const character of value) {
    const nextUnits = visualUnits(character)
    if (current && units + nextUnits > maxUnits) {
      if (/[，。！？；：、,.!?;:）)\]】}]/u.test(character)) {
        lines.push(`${current.trimEnd()}${character}`)
        current = ''
        units = 0
        continue
      }
      lines.push(current.trimEnd())
      current = character.trimStart()
      units = current ? nextUnits : 0
    } else {
      current += character
      units += nextUnits
    }
  }
  if (current || lines.length === 0) lines.push(current.trimEnd())
  return lines
}

function wrapText(value: string, maxUnits: number): string[] {
  const result: string[] = []
  for (const paragraph of value.split('\n')) {
    if (!paragraph.trim()) {
      if (result.at(-1) !== '') result.push('')
      continue
    }
    result.push(...wrapLine(paragraph, maxUnits))
  }
  while (result.at(-1) === '') result.pop()
  return result
}

function textLines(lines: string[], input: {
  x: number
  y: number
  size: number
  lineHeight: number
  fill: string
  weight?: number
}): string {
  return `<text x="${String(input.x)}" y="${String(input.y)}" fill="${input.fill}" font-size="${String(input.size)}" font-weight="${String(input.weight ?? 400)}">${lines.map((line, index) => `<tspan x="${String(input.x)}" dy="${index === 0 ? '0' : String(input.lineHeight)}">${escapeXml(line || ' ')}</tspan>`).join('')}</text>`
}

export function renderConversationShareImage(share: ConversationShareRecord): string {
  const locale = localeOf(share)
  const copy = locale === 'zh-CN' ? {
    brand: 'CODYWEB / 共享对话', readonly: '只读快照', question: '提问', answer: 'CODY', process: '过程',
    turn: '回合', images: '图片未随快照发布', truncated: '内容较长，长图仅展示前半部分。请打开分享链接查看完整对话。',
    footer: '由 CodyWeb 生成 · 公开快照无法访问原 Session', expires: '有效至',
  } : {
    brand: 'CODYWEB / SHARED CONVERSATION', readonly: 'READ-ONLY SNAPSHOT', question: 'QUESTION', answer: 'CODY', process: 'PROCESS',
    turn: 'Turn', images: 'Images are omitted from this snapshot', truncated: 'This conversation is long. Open the shared link to read the complete conversation.',
    footer: 'Generated by CodyWeb · This snapshot cannot access the source session', expires: 'Expires',
  }
  const nodes: string[] = []
  let y = MARGIN
  const titleLines = wrapText(share.title, 34)
  const headerHeight = 154 + titleLines.length * 54
  nodes.push(`<rect x="${String(MARGIN)}" y="${String(y)}" width="${String(CONTENT_WIDTH)}" height="${String(headerHeight)}" rx="28" fill="#ffffff" stroke="#dce3ee"/>`)
  nodes.push(textLines([copy.brand], { x: MARGIN + 34, y: y + 42, size: 17, lineHeight: 24, fill: '#68758a', weight: 700 }))
  nodes.push(`<rect x="${String(WIDTH - MARGIN - 188)}" y="${String(y + 22)}" width="154" height="42" rx="21" fill="#eef4ff"/>`)
  nodes.push(textLines([copy.readonly], { x: WIDTH - MARGIN - 165, y: y + 50, size: 16, lineHeight: 22, fill: '#315d9f', weight: 700 }))
  nodes.push(textLines(titleLines, { x: MARGIN + 34, y: y + 104, size: 42, lineHeight: 54, fill: '#172033', weight: 750 }))
  const expiry = share.expiresAtIso ? `${copy.expires} ${formatDate(share.expiresAtIso, locale)}` : formatDate(null, locale)
  nodes.push(textLines([`${String(share.turnCount)} ${copy.turn.toLocaleLowerCase(locale)} · ${expiry}`], { x: MARGIN + 34, y: y + headerHeight - 28, size: 19, lineHeight: 26, fill: '#68758a' }))
  y += headerHeight + 28

  let previousTurnId = ''
  let turnIndex = 0
  let truncated = false
  for (const message of share.snapshot.messages) {
    const beginsTurn = message.turnId !== previousTurnId
    if (beginsTurn) {
      previousTurnId = message.turnId
      turnIndex += 1
      if (turnIndex > 1) {
        nodes.push(`<line x1="${String(MARGIN + 20)}" x2="${String(WIDTH - MARGIN - 20)}" y1="${String(y)}" y2="${String(y)}" stroke="#dce3ee"/>`)
        y += 34
      }
    }
    const role = message.role === 'user' ? copy.question : message.role === 'assistant' ? copy.answer : copy.process
    const chunks = [plainMarkdown(message.text, locale)]
    if (message.tool) {
      chunks.push([message.tool.title, message.tool.summary, ...message.tool.details, message.tool.output].filter(Boolean).join('\n'))
    }
    if (message.imageCount > 0) chunks.push(`${copy.images} (${String(message.imageCount)})`)
    const lines = wrapText(chunks.filter(Boolean).join('\n'), 34)
    if (lines.length === 0) continue
    const availableLines = Math.max(0, Math.floor((MAX_HEIGHT - y - 240) / BODY_LINE_HEIGHT))
    if (availableLines <= 0) {
      truncated = true
      break
    }
    const visibleLines = lines.slice(0, availableLines)
    if (visibleLines.length < lines.length) truncated = true
    const bodyHeight = Math.max(68, visibleLines.length * BODY_LINE_HEIGHT + 34)
    const label = beginsTurn ? `${role}  ·  ${copy.turn} ${String(turnIndex)}` : role
    nodes.push(textLines([label], { x: MARGIN + 4, y: y + 24, size: 17, lineHeight: 24, fill: '#68758a', weight: 700 }))
    if (message.role === 'user') {
      nodes.push(`<rect x="${String(MARGIN + 148)}" y="${String(y)}" width="${String(CONTENT_WIDTH - 148)}" height="${String(bodyHeight)}" rx="20" fill="#eef4ff" stroke="#cad9ef"/>`)
    } else {
      nodes.push(`<rect x="${String(MARGIN + 148)}" y="${String(y + 4)}" width="5" height="${String(Math.max(42, bodyHeight - 8))}" rx="3" fill="#67a0e8"/>`)
    }
    nodes.push(textLines(visibleLines, { x: MARGIN + 176, y: y + 40, size: BODY_FONT_SIZE, lineHeight: BODY_LINE_HEIGHT, fill: '#172033' }))
    y += bodyHeight + 30
    if (truncated) break
  }

  if (truncated) {
    const noticeLines = wrapText(copy.truncated, 40)
    const noticeHeight = noticeLines.length * 36 + 42
    nodes.push(`<rect x="${String(MARGIN + 148)}" y="${String(y)}" width="${String(CONTENT_WIDTH - 148)}" height="${String(noticeHeight)}" rx="18" fill="#fff6e6" stroke="#f0c879"/>`)
    nodes.push(textLines(noticeLines, { x: MARGIN + 176, y: y + 38, size: 22, lineHeight: 36, fill: '#865b13', weight: 650 }))
    y += noticeHeight + 30
  }
  nodes.push(textLines([copy.footer], { x: MARGIN + 4, y: y + 34, size: 17, lineHeight: 24, fill: '#68758a' }))
  const height = Math.min(MAX_HEIGHT, Math.max(820, y + 74))

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${String(WIDTH)}" height="${String(height)}" viewBox="0 0 ${String(WIDTH)} ${String(height)}"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#eef3fb"/><stop offset="1" stop-color="#f8fafc"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#bg)"/><g font-family="Inter, Noto Sans SC, PingFang SC, Microsoft YaHei, Arial, sans-serif">${nodes.join('')}</g></svg>`
}

export function sendConversationShareImage(res: Response, title: string, svg: string): void {
  const fileName = `${title.trim().replace(/[^\p{L}\p{N}._-]+/gu, '-').slice(0, 100) || 'codyweb-conversation'}.svg`
  res.status(200)
  res.setHeader('Content-Type', 'image/svg+xml; charset=utf-8')
  res.setHeader('Content-Disposition', `inline; filename*=UTF-8''${encodeURIComponent(fileName)}`)
  res.setHeader('Cache-Control', 'no-store')
  res.setHeader('X-Robots-Tag', 'noindex, nofollow, noarchive')
  res.setHeader('Content-Security-Policy', "default-src 'none'; style-src 'none'; script-src 'none'; frame-ancestors 'none'; sandbox")
  res.send(svg)
}
