import { DEFAULT_SKIN_RECIPES, SKIN_API_VERSION } from './tokens'
import type { SkinPack, SkinRecipes, ThemeTokens } from './tokens'

const systemSans = 'Inter, "IBM Plex Sans", "Avenir Next", "Segoe UI", ui-sans-serif, system-ui, sans-serif'
const systemMono = '"IBM Plex Mono", "Cascadia Code", "SFMono-Regular", ui-monospace, monospace'

function tokens(overrides: Partial<ThemeTokens> & { color: ThemeTokens['color'] }): ThemeTokens {
  return {
    color: overrides.color,
    font: overrides.font ?? {
      sans: systemSans,
      mono: systemMono,
    },
    spacing: overrides.spacing ?? {
      xs: '0.25rem',
      sm: '0.625rem',
      md: '0.875rem',
      lg: '1.25rem',
    },
    radius: overrides.radius ?? {
      sm: '0.4rem',
      md: '0.7rem',
      lg: '1rem',
    },
    shadow: overrides.shadow ?? {
      panel: '0 1px 0 rgb(255 255 255 / 0.035), 0 12px 32px rgb(7 10 15 / 0.14)',
      floating: '0 24px 64px rgb(7 10 15 / 0.34)',
      focus: '0 0 0 3px rgb(66 200 245 / 0.22)',
    },
    motion: overrides.motion ?? {
      fast: '120ms',
      normal: '180ms',
      slow: '280ms',
    },
    density: overrides.density ?? 'comfortable',
  }
}

function skin(input: Omit<SkinPack, 'manifest' | 'recipes'> & {
  manifest?: Partial<SkinPack['manifest']>
  recipes?: Partial<SkinRecipes>
}): SkinPack {
  return {
    ...input,
    manifest: {
      schemaVersion: SKIN_API_VERSION,
      version: input.manifest?.version ?? '1.0.0',
      author: input.manifest?.author ?? 'CodyWeb',
      ...(input.manifest?.homepage ? { homepage: input.manifest.homepage } : {}),
      ...(input.manifest?.chromeLabel ? { chromeLabel: input.manifest.chromeLabel } : {}),
    },
    recipes: {
      ...DEFAULT_SKIN_RECIPES,
      ...input.recipes,
    },
  }
}

export const BUILT_IN_SKINS: SkinPack[] = [
  skin({
    id: 'codex-classic',
    name: 'Codex Classic',
    description: 'Quiet, close to the original desktop feel.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#101216', foreground: '#e5e7eb' },
    chartPalette: ['#2563eb', '#16a34a', '#d97706', '#dc2626', '#7c3aed'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f4f4f5',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#ffffff',
        text: '#18181b',
        textMuted: '#71717a',
        border: '#e4e4e7',
        accent: '#2563eb',
        danger: '#dc2626',
        warning: '#d97706',
        success: '#16a34a',
        info: '#2563eb',
        codeBackground: '#18181b',
        terminalBackground: '#101216',
      },
    }),
  }),
  skin({
    id: 'control-tower',
    name: 'Control Tower',
    description: 'Dark, dense, status-forward engineering console.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#05070c', foreground: '#e5e7eb' },
    chartPalette: ['#22c55e', '#38bdf8', '#f59e0b', '#f87171', '#a78bfa'],
    background: { type: 'grid' },
    tokens: tokens({
      color: {
        background: '#0f172a',
        surface: '#111827',
        panel: '#131c2f',
        elevated: '#1e293b',
        text: '#f8fafc',
        textMuted: '#94a3b8',
        border: '#334155',
        accent: '#22c55e',
        danger: '#ef4444',
        warning: '#f59e0b',
        success: '#22c55e',
        info: '#38bdf8',
        codeBackground: '#0b1120',
        terminalBackground: '#0b1120',
      },
      shadow: {
        panel: '0 1px 0 rgb(255 255 255 / 0.035), 0 14px 36px rgb(0 0 0 / 0.22)',
        floating: '0 28px 72px rgb(0 0 0 / 0.52)',
        focus: '0 0 0 3px rgb(34 197 94 / 0.28)',
      },
      density: 'compact',
    }),
  }),
  skin({
    id: 'cyber-ops',
    name: 'Cyber Ops',
    description: 'High-contrast operational skin with strong status colors.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#020617', foreground: '#d9f99d' },
    chartPalette: ['#22d3ee', '#84cc16', '#f97316', '#f43f5e', '#e879f9'],
    background: { type: 'grid' },
    tokens: tokens({
      color: {
        background: '#020617',
        surface: '#07111f',
        panel: '#0b1526',
        elevated: '#111c31',
        text: '#f8fafc',
        textMuted: '#a7f3d0',
        border: '#164e63',
        accent: '#22d3ee',
        danger: '#f43f5e',
        warning: '#f97316',
        success: '#84cc16',
        info: '#38bdf8',
        codeBackground: '#020617',
        terminalBackground: '#020617',
      },
      density: 'compact',
    }),
  }),
  skin({
    id: 'light-pro',
    name: 'Light Pro',
    description: 'Bright office skin for long reading sessions.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#111827', foreground: '#f9fafb' },
    chartPalette: ['#1d4ed8', '#15803d', '#b45309', '#be123c', '#6d28d9'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f8fafc',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#f8fafc',
        text: '#0f172a',
        textMuted: '#64748b',
        border: '#e2e8f0',
        accent: '#1d4ed8',
        danger: '#be123c',
        warning: '#b45309',
        success: '#15803d',
        info: '#0284c7',
        codeBackground: '#0f172a',
        terminalBackground: '#111827',
      },
      density: 'comfortable',
    }),
  }),
  skin({
    id: 'qq-2007',
    name: 'QQ 2007',
    description: 'Blue-silver desktop nostalgia with crisp, readable work surfaces.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#10273d', foreground: '#eaf6ff' },
    chartPalette: ['#1677c8', '#2d9b5f', '#e08a17', '#d94b45', '#7657b5'],
    background: { type: 'solid' },
    manifest: {
      version: '1.0.0',
      author: 'CodyWeb',
      chromeLabel: '2007',
    },
    recipes: {
      chrome: 'glossy',
      navigation: 'classic',
      panel: 'beveled',
      control: 'beveled',
      message: 'rail',
      composer: 'beveled',
      backdrop: 'aero-grid',
    },
    tokens: tokens({
      color: {
        background: '#d9eafa',
        surface: '#c9e1f7',
        panel: '#f8fbff',
        elevated: '#e8f3fd',
        text: '#173752',
        textMuted: '#526f88',
        border: '#77a3ca',
        accent: '#1677c8',
        danger: '#c83d36',
        warning: '#d8790b',
        success: '#207a4c',
        info: '#1677c8',
        codeBackground: '#112b42',
        terminalBackground: '#10273d',
      },
      font: {
        sans: 'Tahoma, "Microsoft YaHei", "Segoe UI", ui-sans-serif, system-ui, sans-serif',
        mono: systemMono,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
      },
      radius: {
        sm: '0.2rem',
        md: '0.3rem',
        lg: '0.45rem',
      },
      shadow: {
        panel: 'inset 0 1px 0 rgb(255 255 255 / 0.92), 0 1px 2px rgb(34 82 122 / 0.18)',
        floating: '0 12px 30px rgb(34 82 122 / 0.28), inset 0 1px 0 rgb(255 255 255 / 0.9)',
        focus: '0 0 0 3px rgb(22 119 200 / 0.25)',
      },
      motion: {
        fast: '120ms',
        normal: '180ms',
        slow: '240ms',
      },
      density: 'compact',
    }),
  }),
  skin({
    id: 'terminal',
    name: 'Terminal',
    description: 'Log-first skin with compact spacing and terminal colors.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#000000', foreground: '#f4f4f5' },
    chartPalette: ['#4ade80', '#22d3ee', '#facc15', '#fb7185', '#c084fc'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#050505',
        surface: '#0a0a0a',
        panel: '#111111',
        elevated: '#18181b',
        text: '#f4f4f5',
        textMuted: '#a1a1aa',
        border: '#27272a',
        accent: '#4ade80',
        danger: '#fb7185',
        warning: '#facc15',
        success: '#4ade80',
        info: '#22d3ee',
        codeBackground: '#000000',
        terminalBackground: '#000000',
      },
      density: 'compact',
    }),
  }),
  skin({
    id: 'mobile-focus',
    name: 'Mobile Focus',
    description: 'Spacious small-screen review skin.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#111827', foreground: '#f9fafb' },
    chartPalette: ['#0ea5e9', '#22c55e', '#f59e0b', '#f43f5e', '#8b5cf6'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f1f5f9',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#f8fafc',
        text: '#111827',
        textMuted: '#64748b',
        border: '#dbe3ef',
        accent: '#0ea5e9',
        danger: '#f43f5e',
        warning: '#f59e0b',
        success: '#22c55e',
        info: '#0ea5e9',
        codeBackground: '#111827',
        terminalBackground: '#111827',
      },
      density: 'spacious',
      radius: {
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
      },
    }),
  }),
]
