import { DEFAULT_SKIN_RECIPES, SKIN_API_VERSION } from './tokens'
import type { SkinPack, SkinRecipes, SkinVariant, ThemeTokens } from './tokens'

const systemSans = 'Inter, "IBM Plex Sans", "Avenir Next", "Segoe UI", ui-sans-serif, system-ui, sans-serif'
const systemMono = '"IBM Plex Mono", "Cascadia Code", "SFMono-Regular", ui-monospace, monospace'

function tokens(overrides: Partial<ThemeTokens> & { color: ThemeTokens['color'] }): ThemeTokens {
  return {
    color: overrides.color,
    font: overrides.font ?? {
      sans: systemSans,
      mono: systemMono,
    },
    spacing: overrides.spacing ?? {
      xs: '0.25rem',
      sm: '0.625rem',
      md: '0.875rem',
      lg: '1.25rem',
    },
    radius: overrides.radius ?? {
      sm: '0.4rem',
      md: '0.7rem',
      lg: '1rem',
    },
    shadow: overrides.shadow ?? {
      panel: '0 1px 0 rgb(255 255 255 / 0.035), 0 12px 32px rgb(7 10 15 / 0.14)',
      floating: '0 24px 64px rgb(7 10 15 / 0.34)',
      focus: '0 0 0 3px rgb(66 200 245 / 0.22)',
    },
    motion: overrides.motion ?? {
      fast: '120ms',
      normal: '180ms',
      slow: '280ms',
    },
    density: overrides.density ?? 'comfortable',
  }
}

function skin(input: Omit<SkinPack, 'manifest' | 'recipes' | 'defaultColorMode' | 'variants'> & SkinVariant & {
  isDark: boolean
  alternate: SkinVariant
  manifest?: Partial<SkinPack['manifest']>
  recipes?: Partial<SkinRecipes>
}): SkinPack {
  const {
    isDark,
    tokens: defaultTokens,
    syntaxTheme: defaultSyntaxTheme,
    terminalTheme: defaultTerminalTheme,
    chartPalette: defaultChartPalette,
    background: defaultBackground,
    alternate,
    ...definition
  } = input
  const defaultColorMode = isDark ? 'dark' : 'light'
  const alternateColorMode = isDark ? 'light' : 'dark'
  return {
    ...definition,
    manifest: {
      schemaVersion: SKIN_API_VERSION,
      version: input.manifest?.version ?? '1.0.0',
      author: input.manifest?.author ?? 'CodyWeb',
      ...(input.manifest?.homepage ? { homepage: input.manifest.homepage } : {}),
      ...(input.manifest?.chromeLabel ? { chromeLabel: input.manifest.chromeLabel } : {}),
    },
    recipes: {
      ...DEFAULT_SKIN_RECIPES,
      ...input.recipes,
    },
    defaultColorMode,
    variants: {
      [defaultColorMode]: {
        tokens: defaultTokens,
        syntaxTheme: defaultSyntaxTheme,
        terminalTheme: defaultTerminalTheme,
        chartPalette: defaultChartPalette,
        ...(defaultBackground ? { background: defaultBackground } : {}),
      },
      [alternateColorMode]: alternate,
    },
  }
}

export const BUILT_IN_SKINS: SkinPack[] = [
  skin({
    id: 'codex-classic',
    name: 'Codex Classic',
    description: 'Quiet, close to the original desktop feel.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#101216', foreground: '#e5e7eb' },
    chartPalette: ['#2563eb', '#16a34a', '#d97706', '#dc2626', '#7c3aed'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f4f4f5',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#ffffff',
        text: '#18181b',
        textMuted: '#71717a',
        border: '#e4e4e7',
        accent: '#2563eb',
        danger: '#dc2626',
        warning: '#d97706',
        success: '#16a34a',
        info: '#2563eb',
        codeBackground: '#18181b',
        terminalBackground: '#101216',
      },
    }),
    alternate: {
      syntaxTheme: 'dark',
      terminalTheme: { background: '#09090b', foreground: '#f4f4f5' },
      chartPalette: ['#60a5fa', '#4ade80', '#fbbf24', '#fb7185', '#a78bfa'],
      background: { type: 'solid' },
      tokens: tokens({
        color: {
          background: '#18181b',
          surface: '#202024',
          panel: '#27272a',
          elevated: '#303036',
          text: '#fafafa',
          textMuted: '#a1a1aa',
          border: '#3f3f46',
          accent: '#60a5fa',
          danger: '#fb7185',
          warning: '#fbbf24',
          success: '#4ade80',
          info: '#38bdf8',
          codeBackground: '#09090b',
          terminalBackground: '#09090b',
        },
      }),
    },
  }),
  skin({
    id: 'control-tower',
    name: 'Control Tower',
    description: 'Dark, dense, status-forward engineering console.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#05070c', foreground: '#e5e7eb' },
    chartPalette: ['#22c55e', '#38bdf8', '#f59e0b', '#f87171', '#a78bfa'],
    background: { type: 'grid' },
    tokens: tokens({
      color: {
        background: '#0f172a',
        surface: '#111827',
        panel: '#131c2f',
        elevated: '#1e293b',
        text: '#f8fafc',
        textMuted: '#94a3b8',
        border: '#334155',
        accent: '#22c55e',
        danger: '#ef4444',
        warning: '#f59e0b',
        success: '#22c55e',
        info: '#38bdf8',
        codeBackground: '#0b1120',
        terminalBackground: '#0b1120',
      },
      shadow: {
        panel: '0 1px 0 rgb(255 255 255 / 0.035), 0 14px 36px rgb(0 0 0 / 0.22)',
        floating: '0 28px 72px rgb(0 0 0 / 0.52)',
        focus: '0 0 0 3px rgb(34 197 94 / 0.28)',
      },
      density: 'compact',
    }),
    alternate: {
      syntaxTheme: 'light',
      terminalTheme: { background: '#102018', foreground: '#ecfdf5' },
      chartPalette: ['#15803d', '#0369a1', '#b45309', '#be123c', '#6d28d9'],
      background: { type: 'grid' },
      tokens: tokens({
        color: {
          background: '#eef4f0',
          surface: '#ffffff',
          panel: '#f7faf8',
          elevated: '#e6efe9',
          text: '#14251b',
          textMuted: '#5f7267',
          border: '#c8d8ce',
          accent: '#15803d',
          danger: '#be123c',
          warning: '#b45309',
          success: '#15803d',
          info: '#0369a1',
          codeBackground: '#102018',
          terminalBackground: '#102018',
        },
        shadow: {
          panel: '0 1px 0 rgb(255 255 255 / 0.75), 0 14px 36px rgb(20 37 27 / 0.1)',
          floating: '0 28px 72px rgb(20 37 27 / 0.18)',
          focus: '0 0 0 3px rgb(21 128 61 / 0.2)',
        },
        density: 'compact',
      }),
    },
  }),
  skin({
    id: 'cyber-ops',
    name: 'Cyber Ops',
    description: 'High-contrast operational skin with strong status colors.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#020617', foreground: '#d9f99d' },
    chartPalette: ['#22d3ee', '#84cc16', '#f97316', '#f43f5e', '#e879f9'],
    background: { type: 'grid' },
    tokens: tokens({
      color: {
        background: '#020617',
        surface: '#07111f',
        panel: '#0b1526',
        elevated: '#111c31',
        text: '#f8fafc',
        textMuted: '#a7f3d0',
        border: '#164e63',
        accent: '#22d3ee',
        danger: '#f43f5e',
        warning: '#f97316',
        success: '#84cc16',
        info: '#38bdf8',
        codeBackground: '#020617',
        terminalBackground: '#020617',
      },
      density: 'compact',
    }),
    alternate: {
      syntaxTheme: 'light',
      terminalTheme: { background: '#062632', foreground: '#ecfeff' },
      chartPalette: ['#0e7490', '#4d7c0f', '#c2410c', '#be123c', '#a21caf'],
      background: { type: 'grid' },
      tokens: tokens({
        color: {
          background: '#ecfeff',
          surface: '#ffffff',
          panel: '#f0fdfa',
          elevated: '#cffafe',
          text: '#12333b',
          textMuted: '#476b73',
          border: '#a5d8df',
          accent: '#0e7490',
          danger: '#be123c',
          warning: '#c2410c',
          success: '#4d7c0f',
          info: '#0369a1',
          codeBackground: '#062632',
          terminalBackground: '#062632',
        },
        density: 'compact',
      }),
    },
  }),
  skin({
    id: 'light-pro',
    name: 'Light Pro',
    description: 'Bright office skin for long reading sessions.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#111827', foreground: '#f9fafb' },
    chartPalette: ['#1d4ed8', '#15803d', '#b45309', '#be123c', '#6d28d9'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f8fafc',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#f8fafc',
        text: '#0f172a',
        textMuted: '#64748b',
        border: '#e2e8f0',
        accent: '#1d4ed8',
        danger: '#be123c',
        warning: '#b45309',
        success: '#15803d',
        info: '#0284c7',
        codeBackground: '#0f172a',
        terminalBackground: '#111827',
      },
      density: 'comfortable',
    }),
    alternate: {
      syntaxTheme: 'dark',
      terminalTheme: { background: '#0b1120', foreground: '#f8fafc' },
      chartPalette: ['#60a5fa', '#4ade80', '#fbbf24', '#fb7185', '#a78bfa'],
      background: { type: 'solid' },
      tokens: tokens({
        color: {
          background: '#111827',
          surface: '#172033',
          panel: '#1f2937',
          elevated: '#273449',
          text: '#f8fafc',
          textMuted: '#aebdd0',
          border: '#3b4a60',
          accent: '#60a5fa',
          danger: '#fb7185',
          warning: '#fbbf24',
          success: '#4ade80',
          info: '#38bdf8',
          codeBackground: '#0b1120',
          terminalBackground: '#0b1120',
        },
        density: 'comfortable',
      }),
    },
  }),
  skin({
    id: 'qq-2007',
    name: 'QQ 2007',
    description: 'Blue-silver desktop nostalgia with crisp, readable work surfaces.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#10273d', foreground: '#eaf6ff' },
    chartPalette: ['#1677c8', '#2d9b5f', '#e08a17', '#d94b45', '#7657b5'],
    background: { type: 'solid' },
    manifest: {
      version: '1.0.0',
      author: 'CodyWeb',
      chromeLabel: '2007',
    },
    recipes: {
      chrome: 'glossy',
      navigation: 'classic',
      panel: 'beveled',
      control: 'beveled',
      message: 'rail',
      identity: 'avatars',
      composer: 'beveled',
      backdrop: 'aero-grid',
    },
    tokens: tokens({
      color: {
        background: '#d9eafa',
        surface: '#c9e1f7',
        panel: '#f8fbff',
        elevated: '#e8f3fd',
        text: '#173752',
        textMuted: '#526f88',
        border: '#77a3ca',
        accent: '#1677c8',
        danger: '#c83d36',
        warning: '#d8790b',
        success: '#207a4c',
        info: '#1677c8',
        codeBackground: '#112b42',
        terminalBackground: '#10273d',
      },
      font: {
        sans: 'Tahoma, "Microsoft YaHei", "Segoe UI", ui-sans-serif, system-ui, sans-serif',
        mono: systemMono,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
      },
      radius: {
        sm: '0.2rem',
        md: '0.3rem',
        lg: '0.45rem',
      },
      shadow: {
        panel: 'inset 0 1px 0 rgb(255 255 255 / 0.92), 0 1px 2px rgb(34 82 122 / 0.18)',
        floating: '0 12px 30px rgb(34 82 122 / 0.28), inset 0 1px 0 rgb(255 255 255 / 0.9)',
        focus: '0 0 0 3px rgb(22 119 200 / 0.25)',
      },
      motion: {
        fast: '120ms',
        normal: '180ms',
        slow: '240ms',
      },
      density: 'compact',
    }),
    alternate: {
      syntaxTheme: 'dark',
      terminalTheme: { background: '#071521', foreground: '#dff3ff' },
      chartPalette: ['#5eb7ff', '#55d58b', '#ffb44c', '#ff7972', '#b79bff'],
      background: { type: 'solid' },
      tokens: tokens({
        color: {
          background: '#0d2234',
          surface: '#132f46',
          panel: '#193a55',
          elevated: '#244c69',
          text: '#edf8ff',
          textMuted: '#a8c5d8',
          border: '#426d8c',
          accent: '#5eb7ff',
          danger: '#ff7972',
          warning: '#ffb44c',
          success: '#55d58b',
          info: '#5eb7ff',
          codeBackground: '#071521',
          terminalBackground: '#071521',
        },
        font: {
          sans: 'Tahoma, "Microsoft YaHei", "Segoe UI", ui-sans-serif, system-ui, sans-serif',
          mono: systemMono,
        },
        spacing: {
          xs: '0.25rem',
          sm: '0.5rem',
          md: '0.75rem',
          lg: '1rem',
        },
        radius: {
          sm: '0.2rem',
          md: '0.3rem',
          lg: '0.45rem',
        },
        shadow: {
          panel: 'inset 0 1px 0 rgb(255 255 255 / 0.12), 0 2px 5px rgb(0 0 0 / 0.35)',
          floating: '0 16px 38px rgb(0 0 0 / 0.5), inset 0 1px 0 rgb(255 255 255 / 0.14)',
          focus: '0 0 0 3px rgb(94 183 255 / 0.28)',
        },
        motion: {
          fast: '120ms',
          normal: '180ms',
          slow: '240ms',
        },
        density: 'compact',
      }),
    },
  }),
  skin({
    id: 'terminal',
    name: 'Terminal',
    description: 'Log-first skin with compact spacing and terminal colors.',
    isDark: true,
    syntaxTheme: 'dark',
    terminalTheme: { background: '#000000', foreground: '#f4f4f5' },
    chartPalette: ['#4ade80', '#22d3ee', '#facc15', '#fb7185', '#c084fc'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#050505',
        surface: '#0a0a0a',
        panel: '#111111',
        elevated: '#18181b',
        text: '#f4f4f5',
        textMuted: '#a1a1aa',
        border: '#27272a',
        accent: '#4ade80',
        danger: '#fb7185',
        warning: '#facc15',
        success: '#4ade80',
        info: '#22d3ee',
        codeBackground: '#000000',
        terminalBackground: '#000000',
      },
      density: 'compact',
    }),
    alternate: {
      syntaxTheme: 'light',
      terminalTheme: { background: '#102317', foreground: '#dcfce7' },
      chartPalette: ['#15803d', '#0e7490', '#a16207', '#be123c', '#7e22ce'],
      background: { type: 'solid' },
      tokens: tokens({
        color: {
          background: '#eef5ef',
          surface: '#f8fcf8',
          panel: '#ffffff',
          elevated: '#e2eee4',
          text: '#15241a',
          textMuted: '#5c6f62',
          border: '#bfd0c2',
          accent: '#15803d',
          danger: '#be123c',
          warning: '#a16207',
          success: '#15803d',
          info: '#0e7490',
          codeBackground: '#102317',
          terminalBackground: '#102317',
        },
        density: 'compact',
      }),
    },
  }),
  skin({
    id: 'mobile-focus',
    name: 'Mobile Focus',
    description: 'Spacious small-screen review skin.',
    isDark: false,
    syntaxTheme: 'light',
    terminalTheme: { background: '#111827', foreground: '#f9fafb' },
    chartPalette: ['#0ea5e9', '#22c55e', '#f59e0b', '#f43f5e', '#8b5cf6'],
    background: { type: 'solid' },
    tokens: tokens({
      color: {
        background: '#f1f5f9',
        surface: '#ffffff',
        panel: '#ffffff',
        elevated: '#f8fafc',
        text: '#111827',
        textMuted: '#64748b',
        border: '#dbe3ef',
        accent: '#0ea5e9',
        danger: '#f43f5e',
        warning: '#f59e0b',
        success: '#22c55e',
        info: '#0ea5e9',
        codeBackground: '#111827',
        terminalBackground: '#111827',
      },
      density: 'spacious',
      radius: {
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
      },
    }),
    alternate: {
      syntaxTheme: 'dark',
      terminalTheme: { background: '#0b1120', foreground: '#f8fafc' },
      chartPalette: ['#38bdf8', '#4ade80', '#fbbf24', '#fb7185', '#a78bfa'],
      background: { type: 'solid' },
      tokens: tokens({
        color: {
          background: '#101827',
          surface: '#172235',
          panel: '#1e2b40',
          elevated: '#29384f',
          text: '#f8fafc',
          textMuted: '#adbad0',
          border: '#3e506b',
          accent: '#38bdf8',
          danger: '#fb7185',
          warning: '#fbbf24',
          success: '#4ade80',
          info: '#38bdf8',
          codeBackground: '#0b1120',
          terminalBackground: '#0b1120',
        },
        density: 'spacious',
        radius: {
          sm: '0.5rem',
          md: '0.75rem',
          lg: '1rem',
        },
      }),
    },
  }),
]
